### PR TITLE
ROS as RTE

### PR DESCRIPTION
**Pull request by francescognn**
## Description
ROS come Run Time Environment per far girare il runner platfom independently.

image
## Done
- Separate node for runner and for emulator
- Created topics, publisher and subscribers for communication
- Fix antifreeze mode
- Fix config for emulator
- Fix unit tests
- Create first acceptance test with ros
- Make launch file to run acceptance tests
- FIx jenkins side

### CODE REVIEW

**Comment by mttgennari** [comment]
recheck

**Comment by francescognn** [comment]
recheck

**Comment by francescognn** [comment]
retest

**Comment by francescognn** [comment]
retest

**Comment by francescognn** [comment]
RETEST

**Comment by francescognn** [comment]
retest

**Comment by francescognn** [comment]
retest

**Comment by francescognn** [comment]
retest

**Review by mttgennari — APPROVED** [review]

**Pull request merged**
